### PR TITLE
Added Yahoo! Finance adapter

### PR DESCRIPTION
**Pull request by jdambacher**
I've created an adapter for the Yahoo YQL service. Now you can receive the latest currency rates from Yahoo and you don't need an API access token.

### CODE REVIEW

**Comment by jdambacher** [comment]
@lexikteam @cedric-g Do you need some more information?

**Comment by cedric-g** [comment]
@jdambacher I hadn't read it yet, can you fix the indentation in the YahooCurrencyAdapter class ? (use spaces)

**Comment by jdambacher** [comment]
@cedric-g Sorry, it's fixed now

**Comment by cedric-g** [comment]
thx :)

**Pull request merged**
